name: jamie_walker_website
description: "Jamie Walker's personal portfolio website"
publish_to: 'none'

version: 1.2.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  easy_localization: ^3.0.3
  collection: ^1.18.0
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_generator: ^2.3.10
  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.4
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.1.0
  auto_size_text: ^3.0.0
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  firebase_storage: ^11.6.4
  firebase_analytics: ^10.8.4
  cloud_firestore: ^4.15.4
  youtube_player_iframe: ^4.0.4
  scroll_to_index: ^3.0.1
  cloud_functions: ^4.6.5
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  responsive_builder: ^0.7.0
  arrow_path: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/google_fonts/nunito/
    - assets/google_fonts/open_sans/
    - assets/images/
    - assets/images/portfolio/joby_one/
    - assets/images/portfolio/joby_one/pages/
    - assets/images/portfolio/joby_motion/
    - assets/images/portfolio/joby_motion/pages/
    - assets/images/portfolio/my_flatmate/
    - assets/images/portfolio/my_flatmate/pages/
    - assets/images/portfolio/manfrotto_motion/
    - assets/images/portfolio/manfrotto_motion/pages/
    - assets/images/portfolio/syrp_genie/
    - assets/images/portfolio/syrp_genie/pages/
    - assets/images/services/
    - assets/images/testimonials/
